models/board.py
from models import Model
from models.user import User 
import time


class Board(Model):
    def __init__(self, form):
        self.id = None
        self.ct = int(time.time())
        self.board_name = form.get("board_name", None)

models/inbox.py
from models import Model, db
import time


class Inbox(Model):
    def __init__(self):
        self.players = []
        self.dialogue = []
        self.ct = int(time.time())
        self.ut = int(time.time())
        self.unmarked = []

    @classmethod
    def get_inbox_item(cls, receiver_mail, sender_mail):
        email_query = [receiver_mail, sender_mail]
        query2 = email_query[::-1]
        if Inbox.find_one(players=email_query) is not None:
            return Inbox.find_one(players=email_query)
        elif Inbox.find_one(players=query2) is not None:
            return Inbox.find_one(players=query2)
        else:
            return None

    @classmethod
    def new(cls, receiver_email, sender_email, content):
        new_inbox = Inbox()
        new_inbox.players.append(sender_email)
        new_inbox.players.append(receiver_email)
        new_inbox.dialogue.append({
            "sender" : sender_email,
            "receiver" : receiver_email,
            "content" : content,
            "ct" : int(time.time()),
        })
        new_inbox.unmarked.append(receiver_email)
        new_inbox.save()
        saved_inbox_item = Inbox.get_inbox_item(receiver_email, sender_email)
        return saved_inbox_item

    def append_dialogue(self, receiver_email, sender_email, content):
        dialogue_item = dict(
            sender = sender_email,
            receiver = receiver_email,
            content = content,
            ct = int(time.time()),
        )
        self.dialogue.append(dialogue_item)
        if receiver_email in self.unmarked:
            pass
        else:
            self.unmarked.append(receiver_email)
        self.update()

    @classmethod
    def find_one(cls, **kwargs):
        """
        根据给定的关键词参数组成的dict,在数据库中寻找相应的数据
        ===
        args
            kwargs: 关键词参数, 给定的查询条件,如author_id=ObjectId(***)
        return
            model: 通过找到的数据重构的一系列实例对象
        """
        data = db[cls.__name__].find_one(kwargs)
        if data is not None:
            i = Inbox()
            for k, v in data.items():
                setattr(i, k, v)
            return i
        return None

    def toggle_mark(self):
        if self.mark == "未读":
            self.mark = "已读"
            self.update()
        elif self.mark == "已读":
            self.mark = "未读"
            self.update()

    @staticmethod
    def dialogue_time(t):
        return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(t))





        

routes/bbs.py
import functools
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
)

from models.user import User
from models.topic import Topic
from models.board import Board

from bson.objectid import ObjectId




main = Blueprint("bbs", __name__)


def current_user():
    email = session.get("email", None)
    user = User.find_by(email=email)
    return user


def login_require(func):
    @functools.wraps(func)
    def wrap(*args, **kwargs):
        u = current_user()
        if u is not None and u.level > 0:
            return func(*args, **kwargs)
        else:
            return redirect(url_for("login.index"))
    return wrap


def admin_require(func):
    @functools.wraps(func)
    def wrap(*args, **kwargs):
        u = current_user()
        if u is not None and u.level == 10:
            return func(*args, **kwargs)
        else:
            return redirect(url_for("login.index"))
    return wrap


@main.route("/", methods=["GET"])
@main.route("/<string:board_id>/", methods=["GET"])
def index(board_id=None):
    boards = Board.all()
    page = int(request.args.get("page", 1))
    if page < 2:
        former_page = None
    else:
        former_page = page - 1
    sort = request.args.get("sort", "ct")
    if (board_id is None) or (board_id == "5a6b00b965d4400b98bcf605"):
        page_number = Topic.get_page_number()
        board = Board.find_by(_id=ObjectId("5a6b00b965d4400b98bcf605"))
        ms = Topic.find_byPage(page, sort)
    else:
        if len(board_id) < 12:
            pass
        else:
            page_number = Topic.get_page_number(board_id)
            board = Board.find_by(_id=ObjectId(board_id))
            ms = Topic.find_byPage(page, sort, board_id=ObjectId(board_id))
    if page_number == page:
        next_page = None
    else:
        next_page = page + 1
    return render_template("BBS/bbs.html",filter=board, pagenumber=page_number,
                           sort=sort, ms=ms, boards=boards, next_page=next_page,
                           former_page=former_page)


@main.route("/search", methods=["GET"])
def search():
    all_topics = Topic.all()
    ret = []
    query = request.args.get("query").lower()
    for i in all_topics:
        if query in i.title.lower():
            ret.append(i)
    return render_template("BBS/search.html", ms=ret)


@main.route("/follow", methods=["POST"])
def follow():
    object_user_id = request.form.get("object_user_id")
    topic_id = request.form.get("topic_id")
    u = current_user()
    if str(u._id) == object_user_id:
        abort(404)
    u.toggle_follow_object(object_user_id)
    return redirect(url_for("topic.detail", topic_id=topic_id))

routes/board.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
)

from models.user import User
from models.board import Board
from .bbs import admin_require, current_user

main = Blueprint("board", __name__)


@main.route("/board", methods=["GET"])
@admin_require
def board():
    u = current_user()
    if u == None:
        return redirect(url_for("bbs.index"))
    else:
        return render_template("BBS/board.html")
    

@main.route("/add", methods=["POST"])
@admin_require
def add():
    form = request.form
    reply = Board.new(form)
    return redirect( url_for("bbs.index"))

routes/inbox.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
)

from bson import ObjectId
from models.user import User
from routes.bbs import current_user, login_require
from models.inbox import Inbox


main = Blueprint("inbox", __name__)


@main.route("/", methods=["GET", "POST"])
@login_require
def index():
    """私信主页面"""
    u = current_user()
    if request.method == "GET":
        inbox_items = [Inbox.find_one(_id=i) for i in u.inbox]
        us = User.all()
        for m in us:
            if m.email == u.email:
                us.remove(m)
        return render_template("BBS/inbox.html", users=us, inbox_items=inbox_items, user=u)
    elif request.method == "POST":
        form = request.form
        print(form)
        receiver = User.find_by(_id=ObjectId(request.form.get("chat-people")))
        dialogue_content = request.form.get("dialogue")
        inbox_item = Inbox.get_inbox_item(receiver.email, u.email)
        if inbox_item is None:
            new_item = Inbox.new(receiver.email, u.email, dialogue_content)
            u.bind_inbox_item(new_item._id)
            receiver.bind_inbox_item(new_item._id)
        else:
            inbox_item.append_dialogue(receiver.email, u.email, dialogue_content)
        return redirect(url_for("inbox.index"))


@main.route("/<string:inbox_id>", methods=["GET", "POST"])
def inbox_detail(inbox_id):
    """私信的详细页面"""
    inbox_item = Inbox.find_one(_id=ObjectId(inbox_id))
    u = current_user()
    if u.email in inbox_item.unmarked:
        inbox_item.unmarked.remove(u.email)
        inbox_item.update()
    inbox_items = [Inbox.find_one(_id=i) for i in u.inbox]
    if u.email == inbox_item.players[0]:
        receiver = inbox_item.players[1]
    else:
        receiver = inbox_item.players[0]
    if request.method == "GET":
        us = User.all()
        for m in us:
            if m.email == u.email:
                us.remove(m)
        return render_template("BBS/inbox_detail.html", inbox_items=inbox_items, user=u,
                               inbox_item=inbox_item)
    elif request.method == "POST":
        dialogue_content = request.form.get("inbox-dialogue")
        inbox_item.append_dialogue(receiver, u.email, dialogue_content)
        return redirect(url_for("inbox.inbox_detail", inbox_id=inbox_id))

routes/login.py
from flask import Flask
from flask import render_template
from flask import redirect
from flask import Blueprint
from flask import make_response
from flask import request
from flask import url_for
from flask import session
from flask import abort

import uuid
import yagmail

from models.user import User
from utils import log
from config import mail_password, mail_user


main = Blueprint("login", __name__)



@main.route("/", methods=["GET"])
def index():
    return make_response(render_template("BBS/login.html"))


@main.route("/register", methods=["GET"])
def register():
    return make_response(render_template("BBS/register.html"))


@main.route("/add", methods=["POST"])
def add_user():
    form = request.form
    user = User(form)
    if user.validate_register() is True:
        token = uuid.uuid1()
        user.token = token
        user.hash_password()
        user.save()
        # 邮箱正文
        url = request.host + url_for(".activate_user") + "?user=" + user.email + "&" + "token=" + str(token)
        contents = [url]
        # 发送邮件
        yag = yagmail.SMTP(user=mail_user, password=mail_password, host='smtp.qq.com')
        yag.send(user.email, '验证激活', contents)
        return redirect(url_for(".index"))
    else:
        return redirect(url_for(".register"))


@main.route("/login", methods=["POST"])
def login():
    form = request.form
    user = User(form)
    if user.validate_login() is True:
        session["email"] = form.get("email")
        return redirect(url_for("bbs.index"))
    else:
        return redirect(url_for(".register"))


@main.route("/activate", methods=["GET"])
def activate_user():
    d = request.args
    u = User.find_by(email=d.get("user"))
    if u is None:
        abort(404)
    if d.get("token"):
        token = d.get("token")
    elif d.get("amp;token"):
        token = d.get("amp;token")
    else:
        abort(404)
    print("token is :", token)
    ans = u.activate_user(token)
    if ans == False:
        abort(404)
    return redirect(url_for("bbs.index"))


@main.route("/log_out", methods=["GET"])
def log_out():
    if session.get("email") is not None:
        session.pop("email")
    return redirect(url_for("bbs.index"))

routes/profile.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
    abort,
)

import os
import uuid
from werkzeug import secure_filename
import yagmail
from utils import log   

from models.user import User
from routes.bbs import current_user
from .bbs import login_require
from config import accept_user_file_type
from config import folder_image_name
from config import mail_password, mail_user


from bson.objectid import ObjectId




main = Blueprint("profile", __name__)

@main.route("/", methods=["GET"])
@login_require
def index():
    u = current_user()
    return make_response(render_template("BBS/profile.html", user=u))


def allow_file(filename):
    return filename.split(".")[-1] in accept_user_file_type


@main.route("/addimage", methods=["POST"])
@login_require
def add_image():
    u = current_user()
    file = request.files["file"]
    if file and allow_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(folder_image_name, filename))
        u.user_image = filename
        u.update()
        return redirect(url_for(".index"))
    else:
        return redirect(url_for(".index"))


@main.route("/<filename>")
def user_img(filename="default.jpg"):
    return send_from_directory(folder_image_name, filename)


@main.route("/edit_user", methods=["post"])
@login_require
def edit_user():
    """
    用户提交表单修改自己的信息
    return
        返回个人信息页面
    """
    user = current_user()
    user = User.find_by(_id=user._id)
    for k, v in request.form.items():
        setattr(user, k, v)
    user.update()
    return redirect(url_for(".index"))


@main.route("/change_password", methods=["GET", "POST"])
def change_password():
    if request.method == "GET":
        user_id = request.args.get("user_id", None)
        u = User.find_by(_id=ObjectId(user_id))
        token = request.args.get("token", None)
        if user_id is None or token is None and u.token != token:
            abort(404)
        return render_template("BBS/change_password.html", user_id=user_id)
    elif request.method == "POST":
        user_id = request.form.get("user_id")
        password = request.form.get("password")
        u = User.find_by(_id=ObjectId(user_id))
        u.password = password
        u.hash_password()
        u.token = None
        u.update()
        return redirect(url_for(".index"))


@main.route("/send_password_email", methods=["GET"])
@login_require
def send_password_email():
    token = uuid.uuid1()
    user = current_user()
    user.token = token
    user.update()
    # 邮箱正文
    url = request.host + url_for(".change_password") + "?user_id=" + str(user._id) + "&" + "token=" + str(token)
    contents = [url]
    # 发送邮件
    yag = yagmail.SMTP(user=mail_user, password=mail_password, host='smtp.qq.com')
    yag.send(user.email, '修改密码', contents)
    return redirect(url_for(".index"))

routes/reply.py
import time
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
)

from models.user import User
from models.topic import Topic
from models.reply import Reply
from .bbs import login_require, current_user

main = Blueprint("reply", __name__)


@main.route("/add", methods=["POST"])
@login_require
def add():
    form = request.form
    user = current_user()
    reply = Reply.new(form, author_id=user._id)
    t = Topic.find_by(_id=reply.topic_id)
    t.rt = int(time.time())
    t.update()
    return redirect(url_for("topic.detail", topic_id=str(reply.topic_id)))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
)

from bson.objectid import ObjectId
from models.topic import Topic
from models.reply import Reply
from models.board import Board
from models.user import User


from .bbs import login_require
from .bbs import current_user
from utils import log

import markdown



main = Blueprint("topic", __name__)


@main.route("/write", methods=["GET"])
@login_require
def topic_write():
    """
    返回发布新话题的文章页面
    """
    boards = Board.find_all()
    return render_template("BBS/topic_write.html", boards=boards)


@main.route("/<topic_id>")
def detail(topic_id):
    t = Topic.find_by(_id=ObjectId(topic_id))
    t.view += 1
    t.update()
    u = current_user()
    topic_writer = User.find_by(_id=ObjectId(t.user_id))
    r = Reply.find_all(topic_id=ObjectId(topic_id))
    topic_writer_topics = Topic.find_by_sort("ct", user_id=ObjectId(topic_writer._id))
    if len(topic_writer_topics) > 10:
        topic_writer_topics = topic_writer_topics[:10]
    if u is not None and topic_writer._id != u._id:
        be_show = topic_writer._id not in u.following_list
    else:
        be_show = None
    if u:
        show_reply = True
    else:
        show_reply = None
    return render_template("BBS/topic_detail.html", t=t, replys=r, u=topic_writer,
                           ts=topic_writer_topics, beshow=be_show, show_reply=show_reply)


@main.route("/add", methods=["POST"])
@login_require
def add():
    form = request.form
    user = current_user()
    Topic.new(form, user_id=user._id)
    return redirect(url_for("bbs.index"))


@main.route("/all/<user_id>", methods=["GET"])
def topic_all(user_id):
    topic_all = Topic.find_all(user_id=ObjectId(user_id))
    return render_template("BBS/search.html", ms=topic_all)

templates/BBS/bbs.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Material Design for Bootstrap fonts and icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">

    <!-- Material Design for Bootstrap CSS -->
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.0.0-beta.4/dist/css/bootstrap-material-design.min.css" integrity="sha384-R80DC0KVBO4GSTw+wZ5x2zn2pu4POSErBkf8/fSFhPXHxvHJydT0CSgAP2Yo2r4I" crossorigin="anonymous">

    <link rel="stylesheet" href="../../static/css/MyCss.css">
    
  </head>
  <body>
  <div>    
    <nav class="navbar navbar-expand-lg navbar-dark bg-blue">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Home</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="http://taojianping.xyz:2002/">TODO</a>
            </li>
          <li class="nav-item">
              <a class="nav-link" href="#">Player</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{{ url_for('bbs.search')}}" method="GET">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="query">
          <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
  </div>
  <div class="container navtool">
      <div class="row">
        <div class="col-md-2 sidetool">
            <a role="button" class="button-add-new-article card btn btn-primary btn-md" href={{ url_for("topic.topic_write") }}>
              发布新话题
            </a>
            <nav id="navbar-example3" class="navbar navbar-light bg-light">
              <nav class="nav nav-pills flex-column">
                <a class="nav-link" href="{{ url_for('profile.index')}}">个人资料</a>
                <a class="nav-link" href="http://taojianping.xyz:2003/">聊天室</a>
                <a class="nav-link" href="{{ url_for('inbox.index') }}">私信</a>
              </nav>
            </nav>
        </div>
        <div class="col-md-10">
            <div class="card text-center">
                <div class="card-header">
                  <ul class="nav nav-pills card-header-pills nav-tabs">
                    {% for board in boards %}
                    <li class="nav-item">
                    <a class="nav-link" href="/{{ board._id }}?sort={{ sort }}"> {{ board.board_name}} </a>
                    </li>
                    {% endfor %}
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Action</a>
                      <div class="dropdown-menu">
                        <a class="dropdown-item" href="/{{ filter._id }}?sort=view">最热讨论</a>
                        <a class="dropdown-item" href="/{{ filter._id }}?sort=ct">最新发布</a>
                        <a class="dropdown-item" href="/{{ filter._id }}?sort=rt">最新回复</a>
                      </div>
                    </li>
                  </ul>
                </div>
                <div class="list-group topic-list">
                    {% for m in ms %}
                    <a href="{{ url_for('topic.detail', topic_id=m._id )}}" class="topic-each-item list-group-item list-group-item-action flex-column align-items-start">
                      <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1 XXX"> {{ m.title }} </h5>
                        <small> {{m.get_time_internal()}} </small>
                      </div>
                      <small> {{ m.get_replynumber() }}/{{ m.view }} </small>
                    </a>
                    {% endfor %}
                  </div>
                <nav aria-label="...">
                    <ul class="pagination justify-content-center">
                      {% if former_page %}
                      <li class="page-item">
                          <a class="page-link" href="/{{ filter._id }}?page={{ former_page }}&sort={{ sort }}">Previous</a>
                      </li>
                      {% else %}
                      <li class="page-item disabled">
                          <a class="page-link" href="#">Previous</a>
                      </li>
                      {% endif %}
                      {% for i in range(pagenumber) %}
                      <li class="page-item"><a class="page-link" href="/{{ filter._id }}?page={{ loop.index }}&sort={{ sort }}"> {{ loop.index }} </a></li>
                      {% endfor %}
                      {% if next_page %}
                      <li class="page-item">
                          <a class="page-link" href="/{{ filter._id }}?page={{ next_page }}&sort={{ sort }}">Next</a>
                      </li>
                      {% else %}
                      <li class="page-item disabled">
                          <a class="page-link" href="#">Next</a>
                      </li>
                      {% endif %}
                    </ul>
                  </nav>
              </div>
        </div>
      </div>
    </div>
        </div>
      </div>
      <div class="function-aera">
          <a class="button-add-new-board" href={{ url_for("board.board") }}>增加板块</a>
          <a class="button-log-out" href={{ url_for("login.log_out") }}>退出登录</a>        
      </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>
    <script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-material-design@4.0.0-beta.4/dist/js/bootstrap-material-design.js" integrity="sha384-3xciOSDAlaXneEmyOo0ME/2grfpqzhhTcM4cE32Ce9+8DW/04AGoTACzQpphYGYe" crossorigin="anonymous"></script>
    <script>$(document).ready(function() { $('body').bootstrapMaterialDesign(); });</script>
  </body>
</html>

templates/BBS/board.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Board</title>
</head>
<body>
    <form action= {{url_for("board.add")}} method="POST">
        <input type="text" name="board_name">
        <button>提交</button>
    </form>
</body>
</html>

templates/BBS/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/BBS/topic_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">        
    <link href="https://cdn.bootcss.com/bootstrap-material-design/4.0.2/bootstrap-material-design.css" rel="stylesheet">
    <link rel="stylesheet" href="../../static/css/MyCss.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">    
    <link rel="stylesheet" href="../../static/css/style.css" />
    <link rel="stylesheet" href="../../static/css/editormd.css" />
    <title> {{ t.title }} </title>
</head>
<body id="topic-detail">
    <div class="topic-detail-side">
        <div class="topic_detail card">
                <div class="topic_header"> {{ t.title }} </div>
                <div class="topic-info">
                    ⏲️ 发布时间： {{ t.to_time() }} &nbsp; | &nbsp; 📝 回复： {{ t.get_replynumber() }} &nbsp; | &nbsp; 🕮 阅读： {{ t.view }} 
                </div>
                <hr class="style-four">
                <div id="doc-content">
                        <textarea style="display:none;"> {{ t.content }}</textarea>
                    </div>
            </div>
        <div class="Reply_aera card">
            <div class="reply_all">
                {% for r in replys %}
                <div class="reply_item">
                        <img class="reply-user-image col-md-2" src= {{ url_for("static", filename= "user_image/" + r.get_replymaker_image() ) }} alt="您的头像" srcset=""/>
                    <ul class="reply-info col-md-10">  
                        <li>
                            <span class="reply-writer-info"> {{r.get_replymaker()}} &nbsp; | &nbsp; {{ r.to_time() }}</span>
                            <span class="reply-floor-info"> {{ loop.index }}楼 </span>
                        </li>                                                          
                        <li>
                            <p class="reply-content">{{ r.content }}</p>                                
                        </li>
                    </ul>                                                                                                     
                    <hr>
                </div>
                {%endfor%}
            </div>
            <div class="Reply_reply">
                {% if show_reply %}
                <form action= {{ url_for("reply.add")}} method="POST">
                <input type="hidden" value= {{ t._id }} name="topic_id">
                <textarea name="content" cols="30" rows="10" placeholder="请输入评论"></textarea>
                <button>提交</button>
                </form>
                {% else %}
                <a href="{{url_for('login.index')}}">登录回复</a>
                {% endif %}
            </div>
        </div>
        </div>
    </div>
    <div class="topic-detail-other-side">
        <div class="user-info card">
            <img src= {{ url_for('static', filename='user_image/' + u.user_image)}}>
            <p>{{ u.username }}</p>
            <a href="{{ url_for('topic.topic_all', user_id=u._id)}}">他的文章</a>
            <form action="{{url_for('bbs.follow')}}" method="post">
                <input type="hidden" name="object_user_id" value="{{u._id}}">
                <input type="hidden" name="topic_id" value="{{t._id}}">
                {% if beshow == True %}
                <button type="submit" class="btn btn-outline-primary">Follow</button>
                {% elif  beshow == False %}
                <button type="submit" class="btn btn-outline-primary">Followed</button>
                {% elif  beshow == None %}
                <button type="submit" disabled="disabled" class="btn btn-outline-primary">Follow</button>
                {% endif %}
            </form>
        </div>
        <div class="user-topic card">
            <tit>他的最新文章</tit>
            <hr>
            {% if ts %}
            {% for t in ts %}
            <a href="{{ url_for('topic.detail', topic_id=t._id )}}">{{ loop.index }}.{{ t.title }}</a>
            {% endfor %}
            {% endif %}
        </div>
    </div>          
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap-material-design/4.0.2/bootstrap-material-design.iife.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap-material-design/4.0.2/bootstrap-material-design.umd.js"></script>
    <script src="../../static/js/editormd.min.js"></script>
    <script src="../../static/lib/marked.min.js"></script>
    <script src="../../static/lib/prettify.min.js"></script>
    <script src="../../static/lib/raphael.min.js"></script>
    <script src="../../static/lib/underscore.min.js"></script>
    <script src="../../static/lib/sequence-diagram.min.js"></script>
    <script src="../../static/lib/flowchart.min.js"></script>
    <script src="../../static/lib/jquery.flowchart.min.js"></script>
    <script type="text/javascript">
        var testEditor;
        $(function() {
            testEditor = editormd("test-editormd", {
                width   : "90%",
                height  : 640,
                syncScrolling : "single",
                path    : "../../static/lib/",
                emoji : true,
                saveHTMLToTextarea : true,
            });
        });
    </script>
    <script type="text/javascript">
        var testEditor;
        $(function () {
            testEditor = editormd.markdownToHTML("doc-content", {//注意：这里是上面DIV的id
                htmlDecode: "style,script,iframe",
                emoji: true,
                taskList: true,
                tex: true, // 默认不解析
                flowChart: true, // 默认不解析
                sequenceDiagram: true, // 默认不解析
                codeFold: true,
        });});
     </script>
</body>
</html>